version: "3.2"

services:
  server:
    container_name: distributor-app
    build:
      context: .
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: distributor-db
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "appDb"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "postgres"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 3
    expose:
      - "5432"

volumes:
  db-data:
